/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const VideoJobInput = IDL.Record({
  'imageAssetId' : IDL.Text,
  'musicTrackId' : IDL.Text,
  'mode' : IDL.Text,
  'subtitlesEnabled' : IDL.Bool,
  'resolution' : IDL.Text,
  'voiceLanguage' : IDL.Text,
  'voiceGender' : IDL.Text,
  'prompt' : IDL.Text,
});
export const VideoJob = IDL.Record({
  'id' : IDL.Int,
  'imageAssetId' : IDL.Text,
  'owner' : IDL.Principal,
  'musicTrackId' : IDL.Text,
  'mode' : IDL.Text,
  'subtitlesEnabled' : IDL.Bool,
  'resolution' : IDL.Text,
  'voiceLanguage' : IDL.Text,
  'voiceGender' : IDL.Text,
  'prompt' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  'addJobComment' : IDL.Func([IDL.Int, IDL.Text], [], []),
  'createJob' : IDL.Func([VideoJobInput], [IDL.Int], []),
  'filterByMode' : IDL.Func([IDL.Text], [IDL.Vec(VideoJob)], ['query']),
  'filterByVoiceGender' : IDL.Func([IDL.Text], [IDL.Vec(VideoJob)], ['query']),
  'getImageAsset' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'getJobComments' : IDL.Func([IDL.Int], [IDL.Vec(IDL.Text)], ['query']),
  'getMusicAsset' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
  'jobsCount' : IDL.Func([], [IDL.Nat], ['query']),
  'transformLanguage' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
  'uploadImageAsset' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  'uploadMusicAsset' : IDL.Func([IDL.Text, ExternalBlob], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const VideoJobInput = IDL.Record({
    'imageAssetId' : IDL.Text,
    'musicTrackId' : IDL.Text,
    'mode' : IDL.Text,
    'subtitlesEnabled' : IDL.Bool,
    'resolution' : IDL.Text,
    'voiceLanguage' : IDL.Text,
    'voiceGender' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const VideoJob = IDL.Record({
    'id' : IDL.Int,
    'imageAssetId' : IDL.Text,
    'owner' : IDL.Principal,
    'musicTrackId' : IDL.Text,
    'mode' : IDL.Text,
    'subtitlesEnabled' : IDL.Bool,
    'resolution' : IDL.Text,
    'voiceLanguage' : IDL.Text,
    'voiceGender' : IDL.Text,
    'prompt' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    'addJobComment' : IDL.Func([IDL.Int, IDL.Text], [], []),
    'createJob' : IDL.Func([VideoJobInput], [IDL.Int], []),
    'filterByMode' : IDL.Func([IDL.Text], [IDL.Vec(VideoJob)], ['query']),
    'filterByVoiceGender' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(VideoJob)],
        ['query'],
      ),
    'getImageAsset' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'getJobComments' : IDL.Func([IDL.Int], [IDL.Vec(IDL.Text)], ['query']),
    'getMusicAsset' : IDL.Func([IDL.Text], [IDL.Opt(ExternalBlob)], ['query']),
    'jobsCount' : IDL.Func([], [IDL.Nat], ['query']),
    'transformLanguage' : IDL.Func([], [IDL.Vec(IDL.Text)], ['query']),
    'uploadImageAsset' : IDL.Func([IDL.Text, ExternalBlob], [], []),
    'uploadMusicAsset' : IDL.Func([IDL.Text, ExternalBlob], [], []),
  });
};

export const init = ({ IDL }) => { return []; };